server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${topicPrefix}${spring.application.name}

topicPrefix: 'd.'
topic:
  test.topic: ${topicPrefix}test.topic
